all: ptr ref enum complex mystring Cdocument

ptr:ptr.cpp
	g++ -o ptr.out ptr.cpp

ref:ref.cpp
	g++ -o ref.out ref.cpp

enum: enum.cpp
	g++ -o enum.out enum.cpp

complex: complex.cpp	
	g++ -o complex.out complex.cpp

mystring:mystring.cpp		
	g++ -o mystring.out mystring.cpp

Cdocument:Cdocument.cpp	
	g++ -o cdocument.out Cdocument.cpp

