all: ptr ref enum complex mystring Cdocument fraction print new memory_using Screen airplane embedded labmda variadicTemplate move test_hash
ptr:ptr.cpp
	g++ -o ptr.out ptr.cpp

ref:ref.cpp
	g++ -o ref.out ref.cpp

enum: enum.cpp
	g++ -o enum.out enum.cpp

complex: complex.cpp	
	g++ -o complex.out complex.cpp

mystring:mystring.cpp		
	g++ -o mystring.out mystring.cpp

Cdocument:Cdocument.cpp	
	g++ -o cdocument.out Cdocument.cpp

fraction: fraction.cpp
	g++ -o fraction.out fraction.cpp

print: print.cpp
	g++ -o print.out print.cpp

new: new.cpp	
	g++ -o new.out new.cpp

memory_using: memory_using.cpp
	g++ -o memory_using.out memory_using.cpp

Screen: Screen.cpp
	g++ -o Screen.out Screen.cpp

airplane: airplane.cpp
	g++ -o airplane.out airplane.cpp

embedded: embedded.cpp
	g++ -o embedded.out embedded.cpp
labmda: labmda.cpp
	g++ -o labmda.out labmda.cpp

variadicTemplate:variadicTemplate.cpp
	g++ -o variadicTemplate.out variadicTemplate.cpp

move: move.cpp
	g++ -o move.out move.cpp

test_hash:test_hash.cpp
	g++ -o test_hash.out test_hash.cpp

clean:
	rm -f ptr ref enum complex mystring Cdocument fraction print new memory_using Screen airplane embedded labmda variadicTemplate move