all: my_shared_ptr test_vector test_smartpoint

my_shared_ptr:my_shared_ptr.cpp
	g++ -o my_shared_ptr.out my_shared_ptr.cpp

test_vector:test_vector.cpp
	g++ -o test_vector.out test_vector.cpp

test_smartpoint:test_smartpoint.cpp
	g++ -o test_smartpoint.out test_smartpoint.cpp